### PR TITLE
Feature/smd 191/test localstack connection

### PR DESCRIPTION
**Pull request by bobbi-hbrown**
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?modal=detail&selectedIssue=SMD-191&quickFilter=815

Adds two tests for local connectivity to the Localstack S3 bucket instance. The docker compose repo must be checked out to the FMD-48/host-complete-data-extract branch for this to work.

### CODE REVIEW

**Comment by bobbi-hbrown** [comment]
pre-commit.ci autofix

**Comment by bobbi-hbrown** [comment]
pre-commit.ci autofix

**Comment by cyrusdobbs** [comment]
Can this be merged with squash when merged pls

**Review by cyrusdobbs — APPROVED** [review]
We may want to refactor this when we connect it up to the real S3 buckets but this is fine for now and proves that we can connect up to LocalStack

**Comment by bobbi-hbrown** [comment]
smd-191 test localstack connection

**Pull request merged**
