### PR TITLE
[#PAB-332] Transform round 3 PSI and Risk Register

### PR DESCRIPTION
**Pull request by nsnape**
https://trello.com/c/97RfNJ9h

### Change description
Transform PSI ready to load into DB ` PrivateInvestments`
Transform and combine Project and programme risks, into `RiskRegister`
Tweak DB table to allow data for cancelled project, as per example (data rows are empty, but cancellation summary provided in risk name column)

- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### CODE REVIEW

**Comment by cyrusdobbs** [comment]
Row 18 of the Risk Register has null values (all but project id and riskname) where the db is defined as non-nullable

**Comment by nsnape** [comment]
> ll values (all bu

Yeah, that's a valid input on the form I think. I changed the nullability of these fields in the DB as part of this PR, to allow for partially completed risks. Might be we add more logic around this as part of validation, after MVP1

**Comment by cyrusdobbs** [comment]
ah my bad I was comparing with the previous versions entity class

**Review by cyrusdobbs — APPROVED** [review]
LGTM

**Pull request merged**
