### PR TITLE
[#PAB-332] Transform round 3 Project Progress and Funding Questions

### PR DESCRIPTION
**Pull request by nsnape**
https://trello.com/c/97RfNJ9h

### Change description

Transform `Programme Progress` ready to load into DB
Transform `Funding Question` ready to load
Minor change to nullability on funding Q DB schema

- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### CODE REVIEW

**Comment by cyrusdobbs** [comment]
We have `date_of_important_milestone` down as a string atm (I think we said it was free text) but the transformed data contains datetimes - can this field actually be a `DataTime`?

**Comment by cyrusdobbs** [comment]
`FundingQuestion.response` data contains `< Select >` - does this want to be null?

**Comment by nsnape** [comment]
> `FundingQuestion.response` data contains `< Select >` - does this want to be null?

I think in this case Im happy to leave is as '< Select >' - as it indicates they failed to choose a drop-down option, rather than leaving a free-text field empty. It's because we have a mix of "indicators" in that column, as the table is "unpivoted"

**Comment by nsnape** [comment]
> We have `ProjectProgress.date_of_important_milestone` down as a string atm (I think we said it was free text) but the transformed data contains datetimes - can this field actually be a `DataTime`?

yeah, I'll change on this PR

**Review by cyrusdobbs — APPROVED** [review]
LGTM

**Pull request merged**
